### ISSUE TITLE
`shell.call()` does not capture output

### ISSUE THREAD

**Issue by jtlaune** [rottencelery/dotty#2]
The `call()` function in `shell.py` doesn't capture output. If we are intending to wrap every `subprocess.run()` call with it, we need this functionality, for example in `jt/sync:sync.sync_git()`.

**Comment by mpcsh** [comment]
It only passes output on errors. I think we should just move to [`duct.py`](https://github.com/oconnor663/duct.py)

**Comment by mpcsh** [comment]
Closing, see #4
